### ISSUE TITLE
Please add SteamUserStats()->IndicateAchievementProgress()

### ISSUE THREAD

**Issue by GregoryAveryWeir** [Ventero/FRESteamWorks#18]
Hi! It looks like SteamUserStats()->IndicateAchievementProgress() isn't yet exposed by the API. This would be a nice thing to have.

**Comment by Ventero** [comment]
Implemented it in https://github.com/Ventero/FRESteamWorks/commit/ec10c128df46186e7cedae72c4f26f060bd7b48d. Let me know if it works for you. Do you want me to upload a new build of the ANE, or are you going to build it yourself?

**Comment by GregoryAveryWeir** [comment]
I did my own build and it works great! Thank you so much for your work on this wrapper.
