### ISSUE TITLE
indicateAchievementProgress() is missing from the ANE

### ISSUE THREAD

**Issue by jaimedominguez** [Ventero/FRESteamWorks#19]
Yeah I have the verison from Dec 2014 and it doesnt have it.
But I am unable to compile the src because i don't have the tools.

Thanks for your work.

**Comment by Ventero** [comment]
Yeah, `indicateAchievementProgress` has been implemented quite recently, and I haven't made a new ANE build in a while. For reference, if you want to get more information about a certain build, you can simply use the version number as git revision identifier, so if you want to e.g. see the revision history of build v0.5-9-gfc68c21, you can look at https://github.com/Ventero/FRESteamWorks/commits/v0.5-9-gfc68c21.

I'll try to get a new build uploaded later today.

**Comment by Ventero** [comment]
New build up at http://dump.ventero.de/FRESteamWorks/v0.5-29-gea3356b/. Let me know if you need anything else.

**Comment by jaimedominguez** [comment]
Wow! you are quick!
Thanks!
This game uses it : www.vortexattack.com 
If you want a steam cd key I can give you one as donation .

Cheers!
