### ISSUE TITLE
getLeaderboardName() returns ID, not community name.

### ISSUE THREAD

**Issue by jaimedominguez** [Ventero/FRESteamWorks#21]
Is there a way to retrieve that public name?

Thanks!

**Comment by Ventero** [comment]
Mh, after looking at the upstream documentation, it seems like this is not supported by the Steamworks SDK. I guess the easiest workaround is to maintain some kind of mapping of id -> community name in your application.

If this is a feature you really care about, you could also post a feature request in the Steamworks developer group.
