### ISSUE TITLE
Binary?

### ISSUE THREAD

**Issue by flashpress** [Ventero/FRESteamWorks#26]
Where can I download the collected ANE library? I use here http://dump.ventero.de/FRESteamWorks/ and I receive an error:
`exception, information=ArgumentError: Error #3500: The extension context does not have a method with the name AIRSteam_Init.`

**Comment by wastedabuser** [comment]
Here is binary: http://essenceworks.com/FRESteamWorks/
I've just built this commit: https://github.com/Ventero/FRESteamWorks/commit/25b5bd64d50408cae74dd62ec269ee7dbfdfecc0 from master
