### ISSUE TITLE
v0.6 on macosx

### ISSUE THREAD

**Issue by fanks** [Ventero/FRESteamWorks#28]
Hi, the latest version of the ANE found on http://dump.ventero.de/FRESteamWorks/v0.6/ gives me the following error on Flash Builder 4.7 on mac: 

<img width="539" alt="screenshot 2016-06-21 13 35 46" src="https://cloud.githubusercontent.com/assets/204639/16228692/bfdbf4e2-37b8-11e6-9a1f-cae80d49b6ff.png">

Is there a version working for macosx available? I've tried the V0.5 version and does not give an error, but I from the changelog I understand that is does not work with more recent AirSDK.

**Comment by Ventero** [comment]
Hey, thanks for the report.

According to [this blog post](http://blogs.adobe.com/flashplayer/2015/12/air-64-bit-on-mac-osx.html) about 64bit AIR on OS X, that's just a quirk by Flash Builder - you should still be able to use the ANE since it explicitly supports the "MacOS-x86-64" platform.

Can you confirm whether that's the case?

**Comment by fanks** [comment]
Thanks for the quick response. I can export a release version but I think I'm missing something. 

This is what I'm trying in FB4.7:

1. Include latest ane
2. Check that extendedDesktop is in supportedProfiles
2. Build release version
3. Copy steam_appid.txt and libsteam_api.dylib to the package Resource folder
4. Start up Steam client
5. Run

When I run the release build Steamworks.init() returns false. I must be missing something.

I've tried your build and package scripts and can build and run the test project without a problem.

**Comment by fanks** [comment]
I figured it out. The steam_appid.txt needs to be included in the MacOS folder. So these works for me with FB4.7:

1. Include latest ane
2. Put steam_api.dll, libsteam_api.dylib and steam_appid.txt in /src 
3. Export release version
4. Copy steam_appid.txt to <package>.app/MacOS folder
5. Start Steam client
6. Run

**Comment by Ventero** [comment]
Sorry for the delay in getting back to you - and good to hear you figured things out. The handling of working directories in OS X app bundles is always a bit awkward, as none of the resources you expect in your working directory when starting the binary are there (the working directory is set to Contents/MacOS, which contains *only* the binary, everything else is put into Contents/Resources)...

Just remember to remove the steam_appid.txt before uploading your game!

Closing this, if you have any other questions feel free to open a new issue.

**Comment by rewb0rn** [comment]
Can someone help me out describing where exactly this .app directory is located? We have the same issue but I don't know where to put the text file..
