### ISSUE TITLE
Why swf in ANE in debug mode?

### ISSUE THREAD

**Issue by AntonRiot** [Ventero/FRESteamWorks#30]
Adobe Scout shows that I running swf in debug mode when I profiling a release build used FRESteamWorks.ane.
I think that you use debug version of swf in ane. And SWF Investigator shows "EnableDebugger2" tag in library.swf

**Comment by Ventero** [comment]
Looks like you're right: According to [the docs](http://help.adobe.com/en_US/flex/using/WS2db454920e96a9e51e63e3d11c0bf69084-7a92.html), the default for `compc` is to set `debug=true` - didn't know about that!
