### ISSUE TITLE
What version of SteamSDK is used in FRESteamWorks v0.6 ?

### ISSUE THREAD

**Issue by AntonRiot** [Ventero/FRESteamWorks#32]
Subj.

I am using the latest FRESteamWorks v0.6 and libsteam_api.dylib from the latest Steam SDK (v1.38a), but I got same with https://github.com/Ventero/FRESteamWorks/issues/25 crush.

**Comment by Ventero** [comment]
If I'm not mistaken, v0.6 was compiled against SDK 1.36 on OS X and 1.37 on Windows (not sure why this mismatch happened). I've also now made true on the promise made in #25 of adding a README.txt to every build that contains some basic information, like the SDK version it was built against.

Are you certain you're seeing the same crash as described in #25? What platform are you on? And do you have a crashdump/traceback I could take a look at?

**Comment by AntonRiot** [comment]
We were tested on macos sierra, OS X El Capitan ver.10.11.4 and OS X 10.10.5
Log: https://www.dropbox.com/s/a91d6n9240oaheh/Doors_Log.txt

**Comment by Ventero** [comment]
From the traceback, it looks like the crash is unrelated to FRESteamWorks. In the traceback in issue #25, you can clearly see that FRESteamWorks is the topmost module on the call stack. In your traceback however, FRESteamWorks does not show up (in fact, the application seems to crash even before initializing the AIR runtime). You can also verify that FRESteamWorks does not show up in the list of loaded modules below the traceback, which means it hasn't executed any code whatsoever yet.

So I'm afraid your crash is completely unrelated to FRESteamWorks.
