### ISSUE TITLE
How to deal the Steam ticket problem?

### ISSUE THREAD

**Issue by mkTiger** [Ventero/FRESteamWorks#36]
I connect my game to our server by steps down:

1) Have SessionTicket from GetAuthSessionTicket
2) GetAuthSessionTicketResponse_t is triggered
3) Taking session ticket value, converting it to hex
4) Submitting to web API GET with the parameters "key" (my publisher web api key), "appid" (my app ID) and "ticket" (the hex session ticket)
5) Receiving the following error:

----------------------------------------------------------------
{
"response": {
"error": {
"errorcode": 101,
"errordesc": "Invalid ticket"
}
}
}
----------------------------------------------------------------

Here is an example of the GET request url format being used (key and ticket masked):

https://api.steampowered.com/ISteamUserAuth/AuthenticateUserTicket/v0001/?appid=5986**&key=472F8B274AA****82BB06B397285F2C6&ticket=140000008b0596358d1515d2d830c617010010018779cf58180000000100000002000000b6b457710000000030a96b010b000000b80000003800000004000000d830c617010010019822090081b457710402010a000000002073c658a022e2580100e86502000100e822090000******db50c071a759c032648dd17550dc25423983baeb3df25824657a82a93972012cc6d55ee427811ed63274ab529b953ec5a67ee4289abb23fe27398f3ca9a6facc423b955831ef2cef8274cd4bf4dc89219bfb073e20cca42fea7dc7cc8a08510a1dc18ed90da67c3825a487bccf594f8996f891506e7d3de958982c980d558

some guy sait it's format prolem, and need to encode or convert ,but I don't know where to do that, in which step to do what ?

thanks a lot and it's very urgent !!!

**Comment by Lachhh** [comment]
I have the exact same problem, always getting Invalid ticket. 
From what I see on the Unity version of this (https://spatialos.improbable.io/docs/reference/8.0/tutorials/mini-tutorials/steam#integrate-steamworks), we need to parse the ByteArray with the "steamTicketLength".  I don't know if this is done within this ANE or not...

**Comment by Lachhh** [comment]
Nvm, Looked at the code, and it seems FRE is doing the length thing.

I don't think it's a format problem because otherwise we get "invalid parameter". 

I'll keep digging.  Let me know if you find anything.

**Comment by Lachhh** [comment]
FOUND IT!
if you call beginAuthSession after you request the ticket,  (Like in the Test exemple provided here), it'll invalid the ticket. I removed that call and it worked for me. 

Found the bug here from the comment : https://support.gamesparks.net/support/discussions/topics/1000078113

**Comment by mkTiger** [comment]
@Lachhh, yes I did it ,and I come back here to tell what I found ,and see you reply.
I thinkd I should be here earlier ! so that I can save two days.

the function beginAuthSession  should be called on server but not on client side.
and the RESPONSE_OnValidateAuthTicketResponse response is also server's work ,need to do nothing when you get this respose.
