### ISSUE TITLE
How to get user's head Icon（or avatar）?

### ISSUE THREAD

**Issue by mkTiger** [Ventero/FRESteamWorks#38]
I find that the Steam Friend API has functions to get User's Avatar ,so that I can change user's head in my own game to the Avatar in steam.

these functions are GetSmallFriendAvatar()，GetMediumFriendAvatar（），GetLargeFriendAvatar（）

but our FRESteamWorks doesn't contains these functions.

someone can help me add them ?

**Comment by flashmandv** [comment]
I have the same problem :( 

It could be done in a very nasty way by loading this url for every player:
http://steamcommunity.com/profiles/STEAM_ID/?xml=1
And then getting the avatar url after parsing the response XML.

That is very nasty and slow way and I'm not going to make it this way. I would rather display default avatar icon. Please @Ventero fix this

**Comment by Ventero** [comment]
Resolved by #43. Call `getSmallFriendAvatar` or `getMediumFriendAvatar`. Builds available at http://dump.ventero.de/FRESteamWorks/v0.7/.
