### ISSUE TITLE
How do I change the AppID?

### ISSUE THREAD

**Issue by obuw** [Ventero/FRESteamWorks#39]
After struggling to run the example from the command line, I managed to get the example working by making an FLA file in Flash CC, setting FRESteamWorksTest as the document class, and adding the latest ANE file from http://dump.ventero.de/FRESteamWorks/ as a library.

However, the AppID is stuck as 480. Creating a steam_appid.txt file and trying to set the id there has no effect. I can't find the number 480 referenced anywhere in the example.

So how am I supposed to change the AppID?

Help would be appreciated.

**Comment by obuw** [comment]
Nevermind! I had a steam_appid.txt file in my SDK directory, I must have put it there while trying to get things working, and then forgot about it.

I think it would be really helpful if the readme instructions mentioned where you need to put the dll and txt files, they are very vague when it comes to this stuff.

**Comment by Ventero** [comment]
Sorry, yeah, I know the documentation really isn't the best in that regard. Reason being that a lot of the information regarding setting up the Steam side of things was covered by an NDA when I originally wrote the readme.

Unfortunately I don't really have the time to work on this project anymore these days - but you're more than welcome to submit a pull request if you want to contribute some better documentation.

**Comment by obuw** [comment]
Oh, an NDA, that's understable then.

Either way, thanks for your great work on this, it works like a charm once set up properly. 

I might try to help out and improve the documentation a little later on, once I'm done with this steam release for our current game.
